<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<RootNamespace>BetterCamera</RootNamespace>
		<LangVersion>default</LangVersion>
		<IsPackable>false</IsPackable>
		<AssemblyVersion>1.0.0.0</AssemblyVersion>
		<FileVersion>1.0.0.0</FileVersion>
		<NeutralLanguage>en-US</NeutralLanguage>
		<AssemblyName>BetterCamera</AssemblyName>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>

	<PropertyGroup>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<EnableDefaultCompileItems>false</EnableDefaultCompileItems>
	</PropertyGroup>

	<ItemGroup>
		<Compile Include="Core.cs" />
	</ItemGroup>

	<ItemGroup>
	  <Reference Include="MelonLoader">
	    <HintPath>..\..\gogh Focus with Your Avatar\MelonLoader\net6\MelonLoader.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine">
	    <HintPath>..\..\gogh Focus with Your Avatar\MelonLoader\Dependencies\Il2CppAssemblyGenerator\UnityDependencies\UnityEngine.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.CoreModule">
	    <HintPath>..\..\gogh Focus with Your Avatar\MelonLoader\Dependencies\Il2CppAssemblyGenerator\UnityDependencies\UnityEngine.CoreModule.dll</HintPath>
	  </Reference>
	</ItemGroup>
</Project>